#pragma once
#include <windows.h>
#pragma warning(disable : 26812) // deprecated api

#define MAX_CHILD 20
#define MAX_PID 100
#define TARGET_DLL "mut_DLL.dll"

// szPipeName為管道名稱
static wchar_t szShMemName[] = L"EnviralMap";
static wchar_t szPipeName[] = L"\\\\.\\pipe\\EnviralPipe";

typedef enum Calls {
	cNtOpenKey,
	cNtOpenKeyEx,
	cNtQueryValueKey,
	cNtCreateKey,
	cNtEnumerateKey,
	cNtEnumerateValueKey,
	cNtCreateFile,
	cNtQueryAttributesFile,
	cNtDeviceIoControlFile,
	cNtQueryVolumeInformationFile,
	cNtQuerySystemInformation,
	cNtQuerySystemInformationEx,
	cNtPowerInformation,
	cNtQueryLicenseValue,
	cNtQueryDirectoryFile,
	cNtQueryInformationProcess,
	cNtQueryDirectoryObject,
	cNtCreateMutant,
	cNtOpenMutant,
	cGetAdaptersAddresses,
	cProcess32FirstW,
	cProcess32NextW,
	cCoCreateInstance,
	cGetModuleHandleW,
	cGetModuleHandleA,
	cGetModuleHandleExW,
	cGetModuleHandleExA,
	cGetAdaptersInfo,
	cSetupDiGetDeviceRegistryPropertyW,
	cSetupDiGetDeviceRegistryPropertyA,
	cGetLastInputInfo,
	cEnumServicesStatusExA,
	cEnumServicesStatusExW,
	cInternetCheckConnectionA,
	cInternetCheckConnectionW,
	cGetWindowRect,
	cGetMonitorInfoA,
	cGetMonitorInfoW,
	cFindWindowA,
	cFindWindowW,
	cFindWindowExA,
	cFindWindowExW,
	cGetCursorPos,
	cGetSystemMetrics,
	cSystemParametersInfoA,
	cSystemParametersInfoW,
	cGetAsyncKeyState,
	cGetForegroundWindow,
	cLoadLibraryExW,
	cLoadLibraryExA,
	cLoadLibraryW,
	cLoadLibraryA,

	CALL_SEPARATOR,	// Call的種類分割

	cNtOpenFile,
	cNtReadFile,
	cNtWriteFile,
	cNtDeleteFile,
	cNtQueryInformationFile,
	cNtSetInformationFile,
	cNtOpenDirectoryObject,
	cNtCreateDirectoryObject,
	cNtCreateUserProcess,
	cNtCreateProcess,
	cNtCreateProcessEx,
	cNtSuspendProcess,
	cNtTerminateProcess,
	cNtMapViewOfSection,
	cNtUnmapViewOfSection,
	cNtMakeTemporaryObject,
	cNtMakePermanentObject,
	cNtWriteVirtualMemory,
	cNtSetInformationProcess,
	cNtGetNextProcess,
	cNtReplaceKey,
	cNtRenameKey,
	cNtSaveKey,
	cNtSaveKeyEx,
	cNtSetValueKey,
	cNtDeleteKey,
	cNtDeleteValueKey,
	cNtOpenTimer,
	cNtQueryTimer,
	cNtCreateTimer,
	cNtQuerySystemTime,
	cNtOpenEvent,
	cNtNotifyChangeKey,
	cNtOpenSemaphore,
	cNtCreateSemaphore,
	cNtLockFile,
	cGetSystemTime,
	cGetLocalTime,
	cCreateProcessInternalW,
	cNtCreateThread,
	cNtCreateThreadEx,
	cURLDownloadToFileW,
	cInternetOpenA,
	cInternetConnectA,
	cInternetConnectW,
	cInternetOpenUrlA,
	cHttpOpenRequestA,
	cHttpOpenRequestW,
	cHttpSendRequestA,
	cHttpSendRequestW,
	cInternetReadFile,
	cDnsQuery_A,
	cDnsQuery_W,
	cGetAddrInfoW,
	cWSAStartup,
	cgethostbyname,
	csocket,
	cconnect,
	csend,
	csendto,
	crecv,
	crecvfrom,
	cbind,
	cWSARecv,
	cWSARecvFrom,
	cWSASend,
	cWSASendTo,
	cWSASocketW,
	cFindResourceExW,
	cFindResourceExA,
	cQueryPerformanceCounter,
	cNtDelayExecution,
	cGetTickCount,

	CALL_BLOCK,		// 會卡住進程的function
	cMessageBoxW,
	cMessageBoxA,
	cMessageBoxExW,
	cMessageBoxExA,
	CALL_END
} Call;

static char DebugCallNames[(UINT)Calls::CALL_END][60] = { "NtOpenKey","NtOpenKeyEx","NtQueryValueKey","NtCreateKey","NtEnumerateKey","NtEnumerateValueKey","NtCreateFile","NtQueryAttributesFile",
"NtDeviceIoControlFile","NtQueryVolumeInformationFile","NtQuerySystemInformation","NtQuerySystemInformationEx","NtPowerInformation","NtQueryLicenseValue","NtQueryDirectoryFile",
"NtQueryInformationProcess","NtQueryDirectoryObject","NtCreateMutant","NtOpenMutant","GetAdaptersAddresses","Process32FirstW","Process32NextW","CoCreateInstance","GetModuleHandleW",
"GetModuleHandleA","GetModuleHandleExW","GetModuleHandleExA","GetAdaptersInfo","SetupDiGetDeviceRegistryPropertyW","SetupDiGetDeviceRegistryPropertyA","GetLastInputInfo",
"EnumServicesStatusExA","EnumServicesStatusExW","InternetCheckConnectionA","InternetCheckConnectionW","GetWindowRect","GetMonitorInfoA","GetMonitorInfoW","FindWindowA","FindWindowW","FindWindowExA",
"FindWindowExW","GetCursorPos","GetSystemMetrics","SystemParametersInfoA","SystemParametersInfoW","GetAsyncKeyState","GetForegroundWindow","LoadLibraryExW","LoadLibraryExA","LoadLibraryW","LoadLibraryA",

"CALL_SEPARATOR",

"NtOpenFile","NtReadFile","NtWriteFile","NtDeleteFile","NtQueryInformationFile","NtSetInformationFile","NtOpenDirectoryObject","NtCreateDirectoryObject","NtCreateUserProcess",
"NtCreateProcess","NtCreateProcessEx","NtSuspendProcess","NtTerminateProcess","NtMapViewOfSection","NtUnmapViewOfSection","NtMakeTemporaryObject",
"NtMakePermanentObject","NtWriteVirtualMemory","NtSetInformationProcess","NtGetNextProcess","NtReplaceKey","NtRenameKey","NtSaveKey","NtSaveKeyEx",
"NtSetValueKey","NtDeleteKey","NtDeleteValueKey","NtOpenTimer","NtQueryTimer","NtCreateTimer","NtQuerySystemTime","NtOpenEvent","NtNotifyChangeKey",
"NtOpenSemaphore","NtCreateSemaphore","NtLockFile","GetSystemTime","GetLocalTime","CreateProcessInternalW","NtCreateThread","NtCreateThreadEx",
"URLDownloadToFileW","InternetOpenA","InternetConnectA","InternetConnectW","InternetOpenUrlA","HttpOpenRequestA","HttpOpenRequestW","HttpSendRequestA",
"HttpSendRequestW","InternetReadFile","DnsQuery_A","DnsQuery_W","GetAddrInfoW","WSAStartup","gethostbyname","socket","connect","send","sendto","recv","recvfrom",
"bind","WSARecv","WSARecvFrom","WSASend","WSASendTo","WSASocketW","FindResourceExW","FindResourceExA","QueryPerformanceCounter","NtDelayExecution","GetTickCount",

"CALL_BLOCK",

"MessageBoxW", "MessageBoxA", "MessageBoxExW", "MessageBoxExA" };